# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


from snakemake.utils import min_version

min_version("6.2.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


# Allow users to fix the underlying OS via singularity.
# singularity: "docker://continuumio/miniconda3"


##### Target rules #####


include: "rules/common.smk"


rule all:
    input:
        [fn_stats_global(f"{batch}") for batch in get_batches()],
        ####################
        [fn_post_compr(f"{batch}") for batch in get_batches()],
        [fn_post_hist_summary(f"{batch}") for batch in get_batches()],
        [fn_post_nscl_summary(f"{batch}") for batch in get_batches()],
        ####################
        [fn_asm_compr(f"{batch}") for batch in get_batches()],
        [fn_asm_hist_summary(f"{batch}") for batch in get_batches()],
        [fn_asm_nscl_summary(f"{batch}") for batch in get_batches()],
        ####################
        [fn_pre_compr(f"{batch}") for batch in get_batches()],
        [fn_pre_hist_summary(f"{batch}") for batch in get_batches()],
        [fn_pre_nscl_summary(f"{batch}") for batch in get_batches()],


##### Modules #####


include: "rules/asm.smk"
include: "rules/pre.smk"
include: "rules/tree.smk"
include: "rules/post.smk"
include: "rules/stats.smk"
include: "rules/other.smk"
