from snakemake.utils import min_version

min_version("6.2.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/common.smk"


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",
    protocol=r"(asm|pre|post)",


# TODO: add genome stats, make it configurable
rule all:
    input:
        fn_stats_batches(),
        #fn_stats_genomes(),


##### Modules #####


include: "rules/asm.smk"
include: "rules/pre.smk"
include: "rules/tree.smk"
include: "rules/post.smk"
include: "rules/stats.smk"
include: "rules/other.smk"
